---
title: "TL_oocystPirAnalysis"
author: "Timothy Little"
date: "27/04/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load required packages
require("Matrix")
library(devtools)
options(stringsAsFactors = FALSE)
library(dplyr)
library(tibble)
library(ggplot2)
library(data.table)
library(stringr)
```

```{r bir_id, message=FALSE, results='hide'}

bir_id <- read.csv("/Users/littlet/Dropbox (The Francis Crick)/Data/genelist_plasmoDB_pirsearch_pberghei.csv") %>% 
  filter(Product.Description == 'PIR protein') %>% 
  select(Gene.ID) %>% 
  .$Gene.ID
```

```{r tmmnorm, echo=FALSE}

#Need to get the .csv file of the tmm logged counts from the zip file.

# unzip('../Expression_Matrices/Smartseq2/SS2_tmmlogcounts.csv.zip', list = TRUE)$Name
sc_tmmnorm <- read.csv(unz('../Expression_Matrices/Smartseq2/SS2_tmmlogcounts.csv.zip',
                           'SS2_tmmlogcounts.csv'),
                       header = TRUE,
                       stringsAsFactors = FALSE,
                       row.names = 1)

#Get the metadata so that we can do some extra classification.

sc_meta <- read.csv('../Expression_Matrices/Smartseq2/SS2_pheno.csv',
                       header = TRUE,
                       stringsAsFactors = FALSE,
                    row.names = 1)
```

```{r data}
molecules <- read.table("../Expression_Matrices/Smartseq2/SS2_counts.csv", header = TRUE, sep = ",", row.names=1, stringsAsFactors = TRUE)
anno <- read.delim("../Expression_Matrices/Smartseq2/SS2_pheno.csv", header = TRUE, sep = ",")


cols <- c("bbSpz" = "navy", "EEF"="darkorange", "Merozoite"="lightpink", "oocyst"="steelblue", "ook" = "turquoise4", "ooSpz" = "lightskyblue", "Ring"="hotpink", "sgSpz"= "royalblue", "Schizont" = "violetred", "Male"="purple", "Female"="purple4", "ookoo" = "mediumturquoise", "Trophozoite"="violet")

mca.qc <- SingleCellExperiment(assays = list(
  counts = as.matrix(molecules),
  logcounts = log2(as.matrix(molecules) + 1)
), colData = anno)


mca.qc.ookoo <- mca.qc[, (colData(mca.qc)$ShortenedLifeStage == "ook") | (colData(mca.qc)$ShortenedLifeStage == "ookoo") | (colData(mca.qc)$ShortenedLifeStage == "oocyst")]
mca.qc.eef <- mca.qc[, (colData(mca.qc)$ShortenedLifeStage == "EEF")]
mca.qc.spz <- mca.qc[, (colData(mca.qc)$ShortenedLifeStage == "bbSpz") | 
                          (colData(mca.qc)$ShortenedLifeStage == "sgSpz") |
                          (colData(mca.qc)$ShortenedLifeStage == "ooSpz")]
mca.qc.idc <- mca.qc[, (colData(mca.qc)$ShortenedLifeStage == "Merozoite") | 
                       (colData(mca.qc)$ShortenedLifeStage == "Ring") |
                       (colData(mca.qc)$ShortenedLifeStage2 == "Schizont") | 
                       (colData(mca.qc)$ShortenedLifeStage2 == "Trophozoite")]
mca.qc.sex <- mca.qc[, (colData(mca.qc)$ShortenedLifeStage2 == "Male") | (colData(mca.qc)$ShortenedLifeStage2 == "Female")]


```

```{r num_pir}

#Need to use ShortenedStage2 and 4 to get the times the Ookinetes/Oocysts were sampled, 
# as they took a timepoint from which they got both and used transcription to separate.

singlecell_counts <- sc_tmmnorm %>% 
  rownames_to_column(var = 'Geneid') %>% 
  reshape2::melt(id.vars = c('Geneid'),
                 variable.name = ('cell'),
                 value.name = ('count')) %>% 
  mutate(cell_type = str_remove(cell, pattern = '_[[:digit:]]+$'),
         ShortenedStage2 = sc_meta$ShortenedLifeStage2[match(cell, sc_meta$sample_id)],
         ShortenedStage4 = sc_meta$ShortenedLifeStage4[match(cell, sc_meta$sample_id)]) %>% 
  mutate(cell_name = case_when(
    ShortenedStage4 == 'Oocyst' & ShortenedStage2 == 'oocyst' ~ 'Oocyst_96h', 
    ShortenedStage4 == 'Oocyst' & ShortenedStage2 == 'ookoo' ~ 'Oocyst_48h',
    ShortenedStage4 == 'Ookinete' & ShortenedStage2 == 'ookoo' ~ 'Ookinete_48h',
    ShortenedStage4 == 'Ookinete' & ShortenedStage2 == 'ook' ~ 'Ookinete_18h_24h',
    TRUE ~ as.character(ShortenedStage4))
  )

#Check
# unique(singlecell_counts$cell_name)
# filter(singlecell_counts, ShortenedStage2 %in% 'ook', ShortenedStage4 %in% 'Ookinete')[1:5,]
```

```{r}
singlecell_counts_pir_df <- singlecell_counts %>% 
  filter(Geneid %in% bir_id) %>% 
  group_by(cell, cell_name) %>% 
  dplyr::summarise(total_pir_counts = sum(count),
                   num_pirs = n_distinct(Geneid[count > 0]))

order <- singlecell_counts_pir_df %>% 
  group_by(cell_name) %>% 
  dplyr::summarise(num_pirs_median = median(num_pirs)) %>% 
  arrange(desc(num_pirs_median)) %>% 
  .$cell_name

(p <- ggplot(
  data = singlecell_counts_pir_df, 
  aes(x = factor(cell_name, 
                 levels = order), 
      y = num_pirs)
) +
    geom_boxplot(outlier.shape = NA) +
    geom_dotplot(binaxis = 'y',
                 stackdir = 'center',
                 # binwidth = 0.02,
                 stackratio = 0.01,
                 dotsize = 0.5,
                 position = position_nudge(x = -0.05, y = 0),
                 alpha = 0.5) +
    labs(x = 'Life cycle stage', y = 'Number of bir genes detected by raw counts') +
    scale_y_continuous(breaks = seq(0,35,5)) +
    coord_cartesian(ylim = c(0, 35)) +
    theme_classic() +
    theme(
      axis.text.x = element_text(angle = 45,
                                 hjust = 1)
    ))
```

```{r}
order <- singlecell_counts_pir_df %>% 
  group_by(cell_name) %>% 
  dplyr::summarise(total_pir_counts_median = median(total_pir_counts)) %>% 
  arrange(desc(total_pir_counts_median)) %>% 
  .$cell_name

(p <- ggplot(
  data = singlecell_counts_pir_df, 
  aes(x = factor(cell_name, 
                 levels = order), 
      y = total_pir_counts)
) +
    geom_boxplot(outlier.shape = NA) +
    geom_dotplot(binaxis = 'y',
                 stackdir = 'center',
                 # binwidth = 0.02,
                 stackratio = 0.075,
                 dotsize = 0.25,
                 position = position_nudge(x = -0.04, y = 0),
                 alpha = 0.5
                 ) +
    labs(x = 'Life cycle stage', y = 'Sum of TMM logged pir gene counts') +
    # scale_y_continuous(breaks = seq(0,35,5)) +
    # coord_cartesian(ylim = c(0, 35)) +
    theme_classic() +
    theme(
      axis.text.x = element_text(angle = 45,
                                 hjust = 1)
    ))

```

